### ISSUE TITLE
How do you deploy with rsync?

### ISSUE THREAD

**Issue by westonplatter** [arenoir/ember-cli-deploy-rsync#1]
I realize this is probably an obvious question, but I'm still having trouble with it.

From the command line, how do I trigger the `upload` function? https://github.com/arenoir/ember-cli-deploy-rsync/blob/master/lib/rsync.js#L18.

I'd be happy to add this to the README once I figure this out.

**Comment by arenoir** [comment]
The upload command gets called by ember-deploy-cli when issuing the deploy command.  It is not well documented but you have to have a revision in git for the deploy to work properly.

**Comment by westonplatter** [comment]
Thanks for the quick response.

Do you have an example of the mentioned git reversion to get it working properly?

**Comment by arenoir** [comment]
First commit some changes and push them to your git repository. Then run `ember deploy` that should compile and upload the assets to the server.  

This addon only syncs the compiled assets it doesn't handle the uploading/activation of the index page.
